version: "3.7"
services:
  elasticsearch:
    restart: always
    container_name: elasticsearch
    hostname: elasticsearch
    image: elasticsearch:5.6.10
    ports:
      - "10611:9200"
      - "10612:9300"
  kibana:
    restart: always
    container_name: kibana
    hostname: kibana
    image: kibana:5.6.10
    ports:
      - "10613:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
