version: "3.7"
services:
  elasticsearch:
    restart: always
    networks:
      - elastic-stack
    container_name: elasticsearch
    hostname: elasticsearch
    image: elasticsearch:5.6.10
    ports:
      - 10611:9200
      - 10612:9300
  kibana:
    restart: always
    networks:
      - elastic-stack
    container_name: kibana
    hostname: kibana
    image: kibana:5.6.10
    ports:
      - 10613:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
  logstash:
    restart: always
    networks:
      - elastic-stack
    container_name: logstash
    hostname: logstash
    image: logstash:5.6.10
    ports:
      - 10614:5044
