version: "3.7"
services:
  redis:
    restart: always
    container_name: redis
    hostname: redis
    image: redis:5.0.1
    ports:
      - "6379:6379"
    secrets:
      - redis-pass
    command: redis-server --requirepass 123456 
