version: "3.7"
services:
  redis:
    restart: always
    network_mode: bridge
    container_name: redis
    hostname: redis
    image: redis:5.0.1
    ports:
      - 6379:6379
    command: redis-server --requirepass 123456
